"use client";
import { eventLabels } from "@/lib/publishing/definitions";
import { useEffect,useState } from "react";
import { readApiResponse } from "@/lib/client-api";
type Stats={connected:number;published:number;scheduled:number;failed:number;events:{at:string;action:string;title:string}[]};
export function OperationalOverview({onSites,onAutomation,onPublishing}:{onSites:()=>void;onAutomation:()=>void;onPublishing:()=>void}) {
  const [stats,setStats]=useState<Stats|null>(null);const [error,setError]=useState("");
  useEffect(()=>{let active=true;fetch("/api/dashboard",{cache:"no-store"}).then(async response=>{const data=await readApiResponse(response) as Stats & {error?:string};if(!response.ok) throw new Error(data.error || "Özet yüklenemedi.");if(active) setStats(data);}).catch(error=>{if(active) setError(error.message);});return()=>{active=false;};},[]);
  return <><div className="manager-heading"><div><span className="section-kicker">ROIstation OS</span><h1>Tüm sitelerin, tek merkezde.</h1><p>Gerçek yayınlar, site bağlantıları ve form talepleri.</p></div><button className="button primary" onClick={onAutomation}>AI taslak oluştur</button></div>{error && <div className="manager-error" role="alert">{error}</div>}<section className="operational-metrics">{[{label:"Doğrulanmış site",value:stats?.connected},{label:"Yayındaki hedef",value:stats?.published},{label:"Planlı hedef",value:stats?.scheduled},{label:"Başarısız hedef",value:stats?.failed}].map(item=><div className="panel" key={item.label}><span>{item.label}</span><strong>{item.value ?? "—"}</strong></div>)}</section><section className="panel operational-actions"><h2>Yayın akışı</h2><p>Önce siteye yayın alanını ekle ve doğrula. İçerik veya formu taslak olarak kaydet, hedef siteleri seçip yayınla. Yayından kaldırma ve silme aynı kayıt üzerinden yapılır.</p><div><button className="button secondary" onClick={onSites}>Siteleri bağla</button><button className="button primary" onClick={onPublishing}>Yayınları yönet / sil</button></div></section><section className="panel operational-actions"><h2>İşlem geçmişi</h2>{stats?.events.length ? stats.events.map((event,index)=><p key={index}>{new Date(event.at).toLocaleString("tr-TR")} · {event.title} · {eventLabels[event.action] || event.action}</p>) : <p>Henüz işlem kaydı yok.</p>}</section></>;
}
