/*
 * Example: JSON-LD end to end — building the site-wide Organization / LocalBusiness node,
 * embedding it safely in HTML, and reading it back the way the scanner does.
 *
 * Demonstrates:
 *   - `schemaFor()`: the business node the optimizer injects into a client site's root layout
 *     (or static index.html). A LocalBusiness subtype is used only for local business types;
 *     address, geo, hours, cuisine and map come only from configured business data,
 *   - safe embedding: `JSON.stringify(value).replace(/</g, "\\u003c")`, so a value containing
 *     "</script>" can never close the script element (used by the connector's article renderer
 *     and by the generated <RoistationSchema /> component),
 *   - the read side: JSON-LD blocks parsed from HTML, nodes flattened across @graph and arrays,
 *     and the `schema-valid` / `schema-present` check logic.
 *
 * Source: lib/seo/fixes.ts (schemaFor, generated roistation-schema component, static index
 *         insertion), connectors/roistation/article.tsx (jsonLd), lib/seo/html.ts (JSON-LD
 *         parsing, schemaNodes, typesOf), lib/seo/scanner.ts (schema checks),
 *         lib/publishing/business.ts (isLocalBusinessType, areaServed)
 *
 * Differences from production: the script-block extraction is lifted out of parseHtml() into
 * `readJsonLd()` (attribute entity decoding omitted); check results are returned as { status, finding } instead of full CheckResult
 * objects from the catalogue in lib/seo/checks.ts.
 */

export type BusinessProfile = {
  name: string; schemaType: string; locality?: string; region?: string; country: string; telephone?: string; email?: string;
  streetAddress?: string; postalCode?: string; openingHours?: string[]; priceRange?: string; servesCuisine?: string[];
  latitude?: number; longitude?: number; mapsUrl?: string; sameAs?: string[]; logo?: string;
};

const localTypes = new Set(["LocalBusiness","Restaurant","MedicalBusiness","Dentist","Physician","HousekeepingService","GeneralContractor","TravelAgency","ProfessionalService","LodgingBusiness","Hotel","Store","HealthAndBeautyBusiness","FoodEstablishment","CafeOrCoffeeShop","HomeAndConstructionBusiness","MedicalClinic"]);
export const isLocalBusinessType = (type: string) => localTypes.has(type);
export function areaServed(profile: BusinessProfile) {
  return [profile.locality, profile.region].filter(Boolean).join(", ") || undefined;
}
const js = (value: unknown) => JSON.stringify(value, null, 2);

/* -------------------------------------------------------------- write side */

export function schemaFor(profile: BusinessProfile, origin: string, strategyLocal: boolean) {
  const local = strategyLocal && isLocalBusinessType(profile.schemaType);
  const node: Record<string, unknown> = { "@context": "https://schema.org", "@type": local ? profile.schemaType : "Organization", "@id": `${origin}/#organization`, name: profile.name, url: `${origin}/` };
  if (profile.logo) node.logo = profile.logo;
  if (profile.telephone) node.telephone = profile.telephone;
  if (profile.email) node.email = profile.email;
  if (profile.sameAs?.length) node.sameAs = profile.sameAs;
  if (local) {
    if (profile.streetAddress || profile.locality) node.address = { "@type": "PostalAddress", ...(profile.streetAddress ? { streetAddress: profile.streetAddress } : {}), ...(profile.postalCode ? { postalCode: profile.postalCode } : {}), ...(profile.locality ? { addressLocality: profile.locality } : {}), ...(profile.region ? { addressRegion: profile.region } : {}), addressCountry: profile.country };
    if (profile.latitude !== undefined && profile.longitude !== undefined) node.geo = { "@type": "GeoCoordinates", latitude: profile.latitude, longitude: profile.longitude };
    if (profile.openingHours?.length) node.openingHours = profile.openingHours;
    if (profile.priceRange) node.priceRange = profile.priceRange;
    if (profile.servesCuisine?.length && profile.schemaType === "Restaurant") node.servesCuisine = profile.servesCuisine;
    const area = areaServed(profile); if (area) node.areaServed = { "@type": "Place", name: area };
    if (profile.mapsUrl) node.hasMap = profile.mapsUrl;
  }
  return node;
}

/** connectors/roistation/article.tsx: `<` is escaped so the payload cannot terminate the script element. */
export const jsonLd = (value: unknown) => JSON.stringify(value).replace(/</g, "\\u003c");

/** Source of components/roistation-schema.tsx as written into a Next.js App Router repo by the optimizer. */
export function roistationSchemaComponent(schema: Record<string, unknown>) {
  return `// Generated by ROIstation from the configured business profile. Keep NAP identical to Google Business Profile.\nconst schema = ${js(schema)};\n\nexport function RoistationSchema() {\n  return <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\\\u003c") }} />;\n}\n`;
}

/** Static sites: the tag inserted before </head> of index.html. */
export const staticSchemaTag = (schema: Record<string, unknown>) => `<script type="application/ld+json">${JSON.stringify(schema).replace(/</g, "\\u003c")}</script>`;

/* --------------------------------------------------------------- read side */

export type JsonLdBlock = { raw: string; data: unknown; error: string | null };

function parseAttrs(source: string): Record<string, string> {
  const attrs: Record<string, string> = {};
  const pattern = /([^\s"'<>/=]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'=<>`]+)))?/g;
  let match: RegExpExecArray | null;
  while ((match = pattern.exec(source))) attrs[match[1].toLowerCase()] = match[2] ?? match[3] ?? match[4] ?? "";
  return attrs;
}

/** The JSON-LD part of lib/seo/html.ts parseHtml(): every <script type="application/ld+json">, parsed or with its parse error. */
export function readJsonLd(html: string): JsonLdBlock[] {
  const withoutComments = html.replace(/<!--[\s\S]*?-->/g, "");
  const scripts: { attrs: Record<string, string>; inner: string }[] = [];
  const pattern = /<script\b([^>]*)>([\s\S]*?)<\/script>/gi;
  let match: RegExpExecArray | null;
  while ((match = pattern.exec(withoutComments))) scripts.push({ attrs: parseAttrs(match[1]), inner: match[2] });
  return scripts.filter((script) => (script.attrs.type || "").toLowerCase().includes("ld+json")).map((script) => {
    const raw = script.inner.trim();
    try { return { raw, data: JSON.parse(raw), error: null }; }
    catch (error) { return { raw, data: null, error: error instanceof Error ? error.message : "JSON parse error" }; }
  });
}

/** All schema.org nodes in the JSON-LD blocks, flattened across @graph and arrays. */
export function schemaNodes(blocksList: JsonLdBlock[]): Record<string, unknown>[] {
  const nodes: Record<string, unknown>[] = [];
  const visit = (value: unknown) => {
    if (Array.isArray(value)) { value.forEach(visit); return; }
    if (!value || typeof value !== "object") return;
    const record = value as Record<string, unknown>;
    if (record["@type"]) nodes.push(record);
    if (record["@graph"]) visit(record["@graph"]);
  };
  for (const block of blocksList) if (block.data) visit(block.data);
  return nodes;
}
export const typesOf = (node: Record<string, unknown>) => (Array.isArray(node["@type"]) ? node["@type"] : [node["@type"]]).filter((type): type is string => typeof type === "string");

/** schema-present / schema-valid / organization-schema as evaluated by the scanner (single page). */
export function schemaChecks(blocks: JsonLdBlock[], microdataTypes: string[] = []) {
  const nodes = schemaNodes(blocks);
  const types = [...new Set([...nodes.flatMap(typesOf), ...microdataTypes])];
  const invalid = blocks.filter((block) => block.error || !block.data).map((block) => `/: ${block.error || "boş blok"}`);
  const missingContext = blocks.filter((block) => block.data && typeof block.data === "object" && !Array.isArray(block.data) && !(block.data as Record<string, unknown>)["@context"]).map(() => "/: @context yok");
  const orgNode = nodes.find((node) => typesOf(node).some((type) => type === "Organization" || type === "LocalBusiness" || isLocalBusinessType(type)));
  return {
    types,
    "schema-present": types.length ? { status: "pass", finding: `Bulunan türler: ${types.join(", ")}` } : { status: "fail", finding: "Hiç schema.org yapısal verisi yok." },
    "schema-valid": !blocks.length ? { status: nodes.length || types.length ? "pass" : "skip", finding: "Doğrulanacak JSON-LD bloğu yok." }
      : invalid.length ? { status: "fail", finding: `${invalid.length} JSON-LD bloğu geçersiz.`, evidence: invalid }
      : missingContext.length ? { status: "warn", finding: "Bazı JSON-LD bloklarında @context eksik.", evidence: missingContext }
      : { status: "pass", finding: `${blocks.length} JSON-LD bloğu geçerli.` },
    "organization-schema": !orgNode ? { status: "fail", finding: "Organization veya LocalBusiness düğümü yok." } : orgNode.name && orgNode.url ? { status: "pass", finding: `${typesOf(orgNode).join("/")}: ${String(orgNode.name)}` } : { status: "warn", finding: "Organization düğümünde name veya url eksik." },
  };
}

/* ------------------------------------------------------------------ demo */

export function demo() {
  const profile: BusinessProfile = { name: "Zeytinlik Restoran </script><b>", schemaType: "Restaurant", locality: "Foça", region: "İzmir", country: "TR", servesCuisine: ["Balık", "Meze"] };
  const schema = schemaFor(profile, "https://zeytinlik.example", true);
  const tag = staticSchemaTag(schema);
  const html = `<html lang="tr"><head>${tag}<script type="application/ld+json">{"@type": "FAQPage",}</script></head><body></body></html>`;
  const blocks = readJsonLd(html);
  return {
    embeddedTag: tag,
    roundTripName: (blocks[0].data as { name: string }).name, // the original string, "</script>" intact after JSON.parse
    checks: schemaChecks(blocks),
    component: roistationSchemaComponent(schemaFor({ ...profile, name: "Zeytinlik Restoran" }, "https://zeytinlik.example", true)),
  };
}

if (/jsonld\.ts$/.test(process.argv[1] ?? "")) { const result = demo(); console.log(JSON.stringify({ ...result, component: undefined }, null, 2)); console.log(`\n${result.component}`); }
